### ISSUE TITLE
Roadmap section / Hardfork section

### ISSUE THREAD

**Issue by Maxnflaxl** [BeamMW/beam-web#197]
- [x] rename to PoC and move "DApp" to 2024
![grafik](https://github.com/BeamMW/beam-web/assets/63856008/2d333605-a4f7-4b51-b06d-0b8bf2d2ec4c)

- [x] the fifth HF was in 2022 and should have the same icon
![grafik](https://github.com/user-attachments/assets/a9d1495e-18f5-49cd-825d-45f7f7c57b42)

- [x] the fourth HF was also in 2022 and should have the same icon
![grafik](https://github.com/user-attachments/assets/6abc951b-c28b-4dbe-b460-9844fa1c08c8)

- [x] the third HF was in 2021 and should have the same icon
![grafik](https://github.com/user-attachments/assets/19ebc76b-428e-4f5a-b752-b6711a36145a)

- [x] the second HF was in 2020 and should have the same icon
![grafik](https://github.com/user-attachments/assets/a31d1985-9568-424a-b3ce-2dffb0daaaca)

- [x] the first HF was in 2019 and should have the same icon
![grafik](https://github.com/user-attachments/assets/37a58726-db3c-4cf8-ab2d-aa6bdbb95228)

- [x] add link to HF section
![grafik](https://github.com/user-attachments/assets/cdf07a0d-8dae-4164-970e-96d71a016ad7)

**Comment by messiisgreat** [comment]
I will fix these soon

**Comment by messiisgreat** [comment]
Hello
Just made PR
Please review [here](https://github.com/BeamMW/beam-web/pull/262)
